### ISSUE TITLE
在api 18(4.3系统)上圆心点击不变色

### ISSUE THREAD

**Issue by fanturbo** [yanzhenjie/CircleTextProgressbar#2]
ColorStateList这个没有起作用。
不影响使用，但是我找了半天也没找到原因，我测试发现4.4以上都是可以的。为什么呢？

**Comment by yanzhenjie** [comment]
可能是手机绘制的问题，你换手机试过吗？

**Comment by fanturbo** [comment]
@yanzhenjie 试过了的，vivo x3l、oppo n5117 和华为c8817l这三个手机都测试了，应该与手机没问题。

**Comment by yanzhenjie** [comment]
可能是代码有点问题，不影响使用的话先用着吧，这个项目蛮简单，暂时不会改动，你可以自己改改。
